require('dotenv').config();

module.exports = {
    appName           : process.env.APP_NAME,
    port              : process.env.APP_PORT || 3000,
    mongoUri          : process.env.MONGO_URI,
    environment       : process.env.NODE_ENV || 'development',
    email_sender      : process.env.EMAIL_SENDER,
    email_user        : process.env.EMAIL_USER,
    email_pass        : process.env.EMAIL_PASS,
    doSpaceEndpoint   : process.env.DO_SPACE_ENDPOINT,
    doSpaceAccessKey  : process.env.DO_SPACE_ACCESS_KEY,
    doSpaceSecretKey  : process.env.DO_SPACE_SECRET_KEY,
    doSpaceBucket     : process.env.DO_SPACE_BUCKET,
    doSpaceRegion     : process.env.DO_SPACE_REGION,
    clientID          : process.env.GITHUB_CLIENT_ID,
    clientSecret      : process.env.GITHUB_CLIENT_SECRET,
    githubCallbackURL : process.env.GITHUB_CALLBACK_URL,
    googleClientID    : process.env.GOOGLE_CLIENT_ID,
    googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
    googleCallbackURL : process.env.GOOGLE_CALLBACK_URL,
    redirectURL       : process.env.REDIRECT_URL,
    paypalClientID    : process.env.PAYPAL_CLIENT_ID,
    paypalSecret      : process.env.PAYPAL_SECRET,
};